version: '3.7'
services:

  rinha-compiladores:
    image: maxwellmonteiro/rinha-compiladores:latest
    volumes:
      - ./files/combination.json:/var/rinha/source.rinha.json
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2GB'
    
    command: ["./rinha-compiladores", "/var/rinha/source.rinha.json"]